### ISSUE TITLE
BOUNTY: Capture Best Practices and Architectural Decisions 

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#119]
We still have only a few Wiki pages. This is a great start and a few people have jumped in to help. Here are some ideas for new wiki pages:

- Overall Swarm Architecture 
- Communication Theory and Best Practices
- Technology Stack Proposals

**Comment by UrbanLegendXV** [comment]
I'm doing some ComfyUI stuff for a bit. 

I'll get on this if someone else doesn't before the time I can.

**Comment by vitaminR** [comment]
@daveshap Why was this closed? I was working on researching this and going to make a Wiki page today. I'm new to bounties do they expire or something?

**Comment by daveshap** [comment]
> @daveshap Why was this closed? I was working on researching this and going to make a Wiki page today. I'm new to bounties do they expire or something?

Yes, keep working on it. I am updating bounties for clarity. Once a new practice has been adopted by the Collective, it no longer needs to be presented up here.

**Comment by tpagne** [comment]
@daveshap is this helpful at all for wiki content? [https://github.com/tpagne/GRC ]

The linked repo is my attempt to draft a blue print of "corporate norms" for any swarm to operate against. Its unclear to me what's needed in the Wiki at this stage so I figured I'd offer something.

Another thought, it might help to put a build these directives/bounties out into a roadmap view to keep folks focused on the imperatives and reduce day dreaming. I'm not sure where I land on that spectrum.

I have a lot of thoughts on documenting the communication between agents. The idea in ChatDev that you only discover the full swarm's discussion after completion is something to be improved. It would be great to have live updates against plans for human operators to review, at least until the perpetual motion machine gets moving.
