### ISSUE TITLE
GPTS example agent wont save when entered into openai gpts

### ISSUE THREAD

**Issue by marktellez** [daveshap/OpenAI_Agent_Swarm#137]
https://github.com/daveshap/OpenAI_Agent_Swarm/tree/main/agents/gpts

This agent wont save when the API token is put in. I have tried classic tokens and fine-grained access tokens. I have tried with and without permissions set.

![ss-draft-unsaved](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/22487431/3da833c4-9cf0-4b82-ab79-fcca884ad78b)

The network tab isnt any use, its a 500 error. I have reported this to OpenAI on their forums as well.

I would love to get this working so I can contribute to Dave's excellent work

**Comment by daveshap** [comment]
While this is an important issue, it is not salient to the project.
