### ISSUE TITLE
BOUNTY: Take a stab at building a tool maker agent

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#18]
Open bounty! Someone please take a stab at using the OpenAI Assistant to create a tool building assistant.

**Comment by OWigginsHay** [comment]
I was actually doing this at work today. A good foundation is tell all assistants that they can "Request_Function" where that is a tool function all assistants have which takes [name, description and schema] where schema is the json schema if the requested function. That is all the info you need to make a new tool and another agent or piece of code can add it programatically on request. Might see if I can make something soon

**Comment by daveshap** [comment]
Screenshots?

**Comment by OWigginsHay** [comment]
Yup give me sec, let me get some together and do an info dump. I don't often use github discussions so sorry if I do this inefficiently

**Comment by OWigginsHay** [comment]
![image](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/23276254/11557bb4-0548-445e-abaf-bf606943f607)
That is the tool function that lets the assistant request a new tool.

![image](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/23276254/08907b13-05d5-4a16-99cb-4ff1e47eaa70)
This is the agent using initiative to request a new tool. I am pretending to be an agent in the layer above as I have not full code system to automate this yet.

Add the schema as a tool
![image](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/23276254/74c7da6f-94a0-4686-b9da-0fb6425ecea7)

![image](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/23276254/ca21b54a-b468-4881-89ba-3dfda068ed6e)

**Comment by OWigginsHay** [comment]
The version I had early was a little cleaner as it generated the JSON schema formatted without escaping characters... this version would need cleanup, but theoretically another assistant could do that

**Comment by daveshap** [comment]
Thanks, I'll play with this tomorrow. Great work

**Comment by daveshap** [comment]
Please submit a PR to integrate this into the tool_maker folder!

**Comment by OWigginsHay** [comment]
So branch and populate with an md file and images. Will that be okay? I'll try add some code to if i get time

**Comment by daveshap** [comment]
You can save it all in the README just make sure to include all instructions, JSON, etc so that people know exactly hwo to do it yeah. Images and screenshots to help would be great.

**Comment by OWigginsHay** [comment]
PRd
