### ISSUE TITLE
manual assistant not working

### ISSUE THREAD

**Issue by Quenos** [daveshap/OpenAI_Agent_Swarm#184]
python run.py  --agents-definition-folder definitions/boss-worker3/
 gives an error:

File "[..]/OpenAI_Agent_Swarm/agents/manual_assistants/logger.py", line 21, in emit
    'name': self.agent.id,
            ^^^^^^^^^^^^^
AttributeError: 'Agent' object has no attribute 'id'

**Comment by thehunmonkgroup** [comment]
fixed by recent commits.
