### ISSUE TITLE
BOUNTY: create a discord connector or orchestrator

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#19]
The idea is simple: let's try using discord as an arena for agent communication

**Comment by jaemil** [comment]
So each agent will be a bot or one single bot that can connects to all of them?

**Comment by givingbacksmiles** [comment]
Is this going to be an option or the only source for logs? I saw in other discussions that Discord was also favored. Just curious.

**Comment by daveshap** [comment]
> Is this going to be an option or the only source for logs? I saw in other discussions that Discord was also favored. Just curious.

Probably just one option. Someone can create a folder called like discord_agent or something.

**Comment by bizrockman** [comment]
Do you have something like this in mind?

https://github.com/mishalhossin/Discord-AI-Chatbot

I tinkered with that last month a little bit after I saw it on YouTube to make community Management.

**Comment by dewmguy** [comment]
something like autocode? https://autocode.com/guides/how-to-build-a-chatgpt-bot/

**Comment by Trevato** [comment]
I messed around with this idea a few weeks back. An interesting caveat to note is a Discord app can only have 1 bot. This limits you to only having a single "agent interface" on the discord side without any hacks.

**Comment by bizrockman** [comment]
Is there a specific reason to use Discord?

Why not using Telegram? Groups can also be created with subgroups, so it could work like Discord can work. Ok on Telegram you are having rate limit. That might be a problem.

@Trevato Can you create a large number of apps? So we could simple live with that the app is a wrapper around a bot, if you can create many apps without any issue. That should work than.

What about thinking about something more specific software for the tasks, like a message queue, an IIRC Channel, Mailbox ;-)

**Comment by Trevato** [comment]
When you use discord you get a lot of things for free:

- a great UI/UX experience
- most scaling problems solved by discord
- a free debugger

It would be wise to stay away from hacks so an implementation isn't immediately deprecated.

**Comment by daveshap** [comment]
i think that Discord is too ambitious right now. After watching the threads and talking with the ACE team, I recognize that there are some milestones to hit first.
