### ISSUE TITLE
SUGGESTION: Genetic algorithm on top of agents swarm

### ISSUE THREAD

**Issue by esshka** [daveshap/OpenAI_Agent_Swarm#22]
Don't you think it would be good to try implementing a genetic (evolutionary) algorithm on top of a swarm of agents? We could encode the initial knowledge and prompts (or any other settings) of the agents as their DNA. Multiply, vary, let the strongest live and the weakest die.

**Comment by daveshap** [comment]
Please move this to discussion as it's not a code implementation
