### ISSUE TITLE
BOUNTY: Experiment and submit PR for multi-agent collaboration

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#69]
Take inspiration from ChatDev and AutoGen. Probably keep chat local between multiple agents for now. Too early for Discord and other platforms. 

Goals:
- Establish best practices for agent-to-agent communication
- Figure out how to quickly instantiate groups of agents with arbitrary configurations and tasks (e.g. spin up teams on the fly)
- Document results, share with collective

**Comment by Nivek92** [comment]
this could serve as a starting point https://github.com/yoheinakajima/GPTvsGPT/blob/main/main.py

**Comment by toshNaik** [comment]
This is a good demonstration of agent-to-agent communication https://www.youtube.com/watch?v=4o8tymMQ5GM

**Comment by daveshap** [comment]
> This is a good demonstration of agent-to-agent communication https://www.youtube.com/watch?v=4o8tymMQ5GM

This is a good deep dive, everyone should watch this at least in part.

**Comment by daveshap** [comment]
I will move this to discussion. https://github.com/daveshap/OpenAI_Agent_Swarm/discussions/93
