### ISSUE TITLE
BOUNTY: Submit PR to move all code into appropriate subfolders

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#70]
![image](https://github.com/daveshap/OpenAI_Agent_Swarm/assets/10718065/8238264c-9841-4132-8222-2c3166af8c84)

Let's keep the root of the repo clean.

**Comment by OWigginsHay** [comment]
Thanks @RomanGoEmpire for clean PR to tidy up the folder structure. I want you to see the changes @daveshap but otherwise I think this is good to close (Although I'm sure we will need periodic codebase cleanup)

**Comment by RomanGoEmpire** [comment]
There should be some documentation and established rules/guidelines for the structure of folders as mentioned in #77. We should consider alternative names for "shared" . It may become disorganized. 

My Initial suggestions are:

**memory/storage:** for data storage-related items
**communication:** for managing inter-agent communication

For these projects, we might consider dividing into:

**demos:** for isolated testing folders
**development:** for the primary project interacting with various parts of the repository.

**Comment by OWigginsHay** [comment]
> Thanks @RomanGoEmpire for clean PR to tidy up the folder structure. I want you to see the changes @daveshap but otherwise I think this is good to close (Although I'm sure we will need periodic codebase cleanup)

Also sorry for breaking the one PR a day rule, but I figured that was preferred over having a broken REPO.

**Comment by daveshap** [comment]
You have an exception @OWigginsHay now. That rule was mainly to tamp down on folks submitting multiple trivial PRs in a row
