### ISSUE TITLE
BOUNTY: Document Best Practices on new Wiki Page

### ISSUE THREAD

**Issue by daveshap** [daveshap/OpenAI_Agent_Swarm#91]
https://github.com/daveshap/OpenAI_Agent_Swarm/wiki/Assistant-Best-Practices

I've seen some remarkable improvements with new GPTs and Assistants. Please start capturing your best practices on the Wiki for easy reference. This includes the Concierge GPTs, toolmaker GPTs, and others.

**Comment by daveshap** [comment]
This may be ideal for the GPT Assistants. If someone can create an Assistant that can help surface key documentation points, best practices, and insights, that would be phenomenal.

**Comment by UrbanLegendXV** [comment]
I'm aiming to dive into assistants tonight or tomorrow. I've been focused on GPTs and other stuff. I'll post prompts, codes, findings and such to the wiki when I get a moment to update.

**Comment by daveshap** [comment]
Some folks have started documenting best practices.
